name: Update README with repositories

on:
  schedule:
    - cron: "0 0 * * *"  # Exécute tous les jours à minuit UTC
  push:
    branches:
      - main  # Déclenchement lors de push sur la branche principale
  workflow_dispatch:  # Permet d'exécuter manuellement le workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup pnpm
        run: |
          curl -fsSL https://get.pnpm.io/install.sh | sh -  # Installe pnpm
          echo "export PATH=$HOME/.local/share/pnpm:$PATH" >> $GITHUB_ENV  # Ajoute pnpm au PATH
          pnpm --version  # Vérifie que pnpm est installé correctement

      - name: Install dependencies with pnpm
        run: pnpm install  # Installer les dépendances

      - name: Setup jq
        run: sudo apt-get install jq

      - name: Fetch repositories and update README
        run: |
          USER="loicwr"  # Remplace par ton nom d'utilisateur GitHub
          README_FILE="README.md"

          # Récupérer la liste des dépôts via l'API GitHub
          repos=$(curl -s "https://api.github.com/users/$USER/repos?per_page=100" | jq -r '.[].html_url')

          # Créer ou mettre à jour le fichier README.md
          echo "# Bienvenue sur mon profil GitHub" > $README_FILE
          echo "" >> $README_FILE
          echo "Voici la liste de tous mes dépôts : " >> $README_FILE
          echo "" >> $README_FILE

          for repo in $repos; do
            echo "- [$repo]($repo)" >> $README_FILE
          done

      - name: Commit changes
        run: |
          git config --global user.name "Ton Nom"  # Remplace par ton nom
          git config --global user.email "ton.email@example.com"  # Remplace par ton email
          git add README.md
          git commit -m "Mise à jour de la liste des dépôts"
          git push origin main